<?php

namespace Database\Seeders;

use App\Models\WalkingJourney;
use App\Models\WalkingPointRule;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use RuntimeException;

class WalkingPointRuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $generalJourney = WalkingJourney::where('key', 'general')->first();
        $youthJourney = WalkingJourney::where('key', 'youth')->first();

        if (!$generalJourney || !$youthJourney) {
            throw new RuntimeException('As jornadas general e youth precisam existir antes de executar WalkingPointRuleSeeder.');
        }

        $rules = [
            [
                'walking_journey_id' => $generalJourney->id,
                'key' => 'general_service_attendance',
                'name' => 'Presença no culto',
                'description' => 'Pontuação base para presença validada em culto da igreja.',
                'category' => 'presence',
                'points' => 10,
                'validation_type' => 'leader_validation',
                'source_origin' => 'future_attendance',
                'daily_limit' => 20,
                'weekly_limit' => 40,
                'monthly_limit' => 160,
                'counts_for_level' => true,
                'counts_for_highlight' => true,
                'is_fixed_system_rule' => true,
                'can_edit_points' => true,
                'is_active' => true,
            ],
            [
                'walking_journey_id' => $generalJourney->id,
                'key' => 'general_bible_study_participation',
                'name' => 'Participação em estudo bíblico/culto no lar',
                'description' => 'Pontuação para participação validada em estudo bíblico ou culto no lar.',
                'category' => 'bible_study',
                'points' => 12,
                'validation_type' => 'leader_validation',
                'source_origin' => 'future_attendance',
                'daily_limit' => null,
                'weekly_limit' => 36,
                'monthly_limit' => null,
                'counts_for_level' => true,
                'counts_for_highlight' => true,
                'is_fixed_system_rule' => false,
                'can_edit_points' => true,
                'is_active' => true,
            ],
            [
                'walking_journey_id' => $generalJourney->id,
                'key' => 'general_ministry_service',
                'name' => 'Serviço em ministério/departamento',
                'description' => 'Pontuação para serviço validado em ministério ou departamento.',
                'category' => 'service',
                'points' => 15,
                'validation_type' => 'leader_validation',
                'source_origin' => 'future_department_service',
                'daily_limit' => null,
                'weekly_limit' => 60,
                'monthly_limit' => null,
                'counts_for_level' => true,
                'counts_for_highlight' => true,
                'is_fixed_system_rule' => false,
                'can_edit_points' => true,
                'is_active' => true,
            ],
            [
                'walking_journey_id' => $generalJourney->id,
                'key' => 'general_confirmed_visitor',
                'name' => 'Visitante confirmado indicado/acompanhado',
                'description' => 'Pontuação para visitante confirmado com indicação ou acompanhamento.',
                'category' => 'evangelism',
                'points' => 25,
                'validation_type' => 'secretary_validation',
                'source_origin' => 'future_visitor_followup',
                'daily_limit' => null,
                'weekly_limit' => 100,
                'monthly_limit' => null,
                'counts_for_level' => true,
                'counts_for_highlight' => true,
                'is_fixed_system_rule' => false,
                'can_edit_points' => true,
                'is_active' => true,
            ],
            [
                'walking_journey_id' => $generalJourney->id,
                'key' => 'general_devotional_record',
                'name' => 'Leitura bíblica/devocional registrado',
                'description' => 'Pontuação para registro devocional preparado para fluxo futuro.',
                'category' => 'devotional',
                'points' => 8,
                'validation_type' => 'manual',
                'source_origin' => 'future_devotional_entry',
                'daily_limit' => 8,
                'weekly_limit' => 56,
                'monthly_limit' => null,
                'counts_for_level' => true,
                'counts_for_highlight' => false,
                'is_fixed_system_rule' => false,
                'can_edit_points' => true,
                'is_active' => true,
            ],
            [
                'walking_journey_id' => $generalJourney->id,
                'key' => 'general_community_action',
                'name' => 'Participação em ação de comunhão/serviço',
                'description' => 'Pontuação para ações saudáveis de comunhão e serviço.',
                'category' => 'communion',
                'points' => 12,
                'validation_type' => 'leader_validation',
                'source_origin' => 'future_community_action',
                'daily_limit' => null,
                'weekly_limit' => 48,
                'monthly_limit' => null,
                'counts_for_level' => true,
                'counts_for_highlight' => true,
                'is_fixed_system_rule' => false,
                'can_edit_points' => true,
                'is_active' => true,
            ],
            [
                'walking_journey_id' => $generalJourney->id,
                'key' => 'general_intercession_validated',
                'name' => 'Intercessão validada com cuidado pastoral',
                'description' => 'Regra futura e inativa para fluxo seguro de intercessão, sem ranking de intercessores.',
                'category' => 'intercession',
                'points' => 8,
                'validation_type' => 'pastoral_validation',
                'source_origin' => 'future_intercession_safe_flow',
                'daily_limit' => null,
                'weekly_limit' => 32,
                'monthly_limit' => null,
                'counts_for_level' => true,
                'counts_for_highlight' => false,
                'is_fixed_system_rule' => false,
                'can_edit_points' => true,
                'is_active' => false,
            ],
            [
                'walking_journey_id' => $youthJourney->id,
                'key' => 'youth_resgatados_attendance',
                'name' => 'Presença nos Resgatados',
                'description' => 'Pontuação para presença validada em encontro dos Resgatados.',
                'category' => 'presence',
                'points' => 12,
                'validation_type' => 'leader_validation',
                'source_origin' => 'future_youth_attendance',
                'daily_limit' => null,
                'weekly_limit' => 36,
                'monthly_limit' => null,
                'counts_for_level' => true,
                'counts_for_highlight' => true,
                'is_fixed_system_rule' => false,
                'can_edit_points' => true,
                'is_active' => true,
            ],
            [
                'walking_journey_id' => $youthJourney->id,
                'key' => 'youth_bible_ready',
                'name' => 'Levar Bíblia/anotações para encontro jovem',
                'description' => 'Pontuação para incentivo ao preparo bíblico nos encontros jovens.',
                'category' => 'bible',
                'points' => 6,
                'validation_type' => 'leader_validation',
                'source_origin' => 'future_youth_checkin',
                'daily_limit' => null,
                'weekly_limit' => 18,
                'monthly_limit' => null,
                'counts_for_level' => true,
                'counts_for_highlight' => true,
                'is_fixed_system_rule' => false,
                'can_edit_points' => true,
                'is_active' => true,
            ],
            [
                'walking_journey_id' => $youthJourney->id,
                'key' => 'youth_bible_challenge',
                'name' => 'Participação em desafio bíblico jovem',
                'description' => 'Pontuação para participação validada em desafio bíblico jovem.',
                'category' => 'bible_challenge',
                'points' => 15,
                'validation_type' => 'leader_validation',
                'source_origin' => 'future_youth_challenge',
                'daily_limit' => null,
                'weekly_limit' => 45,
                'monthly_limit' => null,
                'counts_for_level' => true,
                'counts_for_highlight' => true,
                'is_fixed_system_rule' => false,
                'can_edit_points' => true,
                'is_active' => true,
            ],
            [
                'walking_journey_id' => $youthJourney->id,
                'key' => 'youth_service_support',
                'name' => 'Serviço/apoio em escala jovem',
                'description' => 'Pontuação para serviço e apoio validado no contexto jovem.',
                'category' => 'service',
                'points' => 15,
                'validation_type' => 'leader_validation',
                'source_origin' => 'future_youth_service',
                'daily_limit' => null,
                'weekly_limit' => 60,
                'monthly_limit' => null,
                'counts_for_level' => true,
                'counts_for_highlight' => true,
                'is_fixed_system_rule' => false,
                'can_edit_points' => true,
                'is_active' => true,
            ],
            [
                'walking_journey_id' => $youthJourney->id,
                'key' => 'youth_confirmed_visitor',
                'name' => 'Visitante jovem confirmado',
                'description' => 'Pontuação para visitante jovem confirmado e acompanhado.',
                'category' => 'evangelism',
                'points' => 25,
                'validation_type' => 'leader_validation',
                'source_origin' => 'future_youth_visitor_followup',
                'daily_limit' => null,
                'weekly_limit' => 100,
                'monthly_limit' => null,
                'counts_for_level' => true,
                'counts_for_highlight' => true,
                'is_fixed_system_rule' => false,
                'can_edit_points' => true,
                'is_active' => true,
            ],
        ];

        foreach ($rules as $rule) {
            WalkingPointRule::updateOrCreate(
                ['key' => $rule['key']],
                $rule
            );
        }
    }
}
